Feat: use exactly once filter
Informatievlaanderen/VSDS-Linked-Data-Interactions pull request #532
Opened 2024-03-07 12:40 UTC by pj-cegeka

2024-03-10 17:30 UTC, Tomvbe requested changes

2024-03-11 15:37 UTC, pj-cegeka commented on ldi-core/ldes-client/tree-node-supplier/src/main/java/ldes/client/treenodesupplier/repository/sql/TreeNodeRecordEntity.java
> +	private List<String> members;
This is to keep the functionality of not processing the same member within a fragment when we refetch it

2024-03-12 10:08 UTC, Tomvbe commented on ldi-core/ldes-client/tree-node-supplier/src/main/java/ldes/client/treenodesupplier/TreeNodeProcessor.java
> +		treeNodeRecord.addToReceived(newMembers.stream().map(TreeMember::getMemberId).toList());
Is this saved to the database? Since we are at the end of the method?

2024-03-13 08:38 UTC, Tomvbe approved these changes

2024-03-13 13:12 UTC, merged